# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'rn5504' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for rn5504

  pod 'react-native-fast-image', :path => '../node_modules/react-native-fast-image'

end
